services:
  api:
    build: .  # Directory containing Flask app and Dockerfile
    container_name: api
    ports:
      - "5000:5000"
  
  nginx:
    build: ./frontend/
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount your custom nginx.conf
    depends_on:
      - api  # Ensure the API container starts first
